# fly.toml app configuration file generated for transparent-gateway on 2025-06-26T16:37:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'transparent-gateway'
primary_region = 'sea'

[build]

[env]
APP_DOMAIN = 'transparent-gateway.fly.dev'
LUCKY_ENV = 'production'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
